## **Defining Matrices**

In [2]:
import numpy as np

A = np.array([[1,2,-7],[-3,4,-2],[-6,-3,9]])
B = np.array([[1,-5,3],[-2,-4,-6],[8,5,-4]])

## **Transpose of matrix**

In [5]:
print("Transpose of Matrix A:")
print(A.transpose())

print("Transpose of Matrix B:")
print(B.transpose())

Transpose of Matrix A:
[[ 1 -3 -6]
 [ 2  4 -3]
 [-7 -2  9]]
Transpose of Matrix B:
[[ 1 -2  8]
 [-5 -4  5]
 [ 3 -6 -4]]


## **Adding of matrices**

In [6]:
print("Addtion of Matrix A and B:")
print(A+B)

Addtion of Matrix A and B:
[[ 2 -3 -4]
 [-5  0 -8]
 [ 2  2  5]]


## **Subtraction of matrices**

In [7]:
print("Subtraction of Matrix A and B:")
print(A-B)

Subtraction of Matrix A and B:
[[  0   7 -10]
 [ -1   8   4]
 [-14  -8  13]]


## **Multiplication of matrices**

In [8]:
print("Multiplication of Matrix A and B:")
print(A*B)

Multiplication of Matrix A and B:
[[  1 -10 -21]
 [  6 -16  12]
 [-48 -15 -36]]
