## **Defining Matrices**

In [1]:
import numpy as np

A = np.array([[1,2,-7],[-3,4,-2],[-6,-3,9]])
B = np.array([[1,-5,3],[-2,-4,-6],[8,5,-4]])

## **Converting matrix data to absolute values**

In [2]:
X = np.absolute(A)
Y = np.absolute(B)

print("Absolute values in Matrix A:")
print(X)

print("Absolute values in Matrix B:")
print(Y)

Absolute values in Matrix A:
[[1 2 7]
 [3 4 2]
 [6 3 9]]
Absolute values in Matrix B:
[[1 5 3]
 [2 4 6]
 [8 5 4]]


## **Negative of matrices**

In [3]:
X = np.negative(A)
Y = np.negative(B)

print("Negative values of Matrix A:")
print(X)

print("Negative values of Matrix B:")
print(Y)

Negative values of Matrix A:
[[-1 -2  7]
 [ 3 -4  2]
 [ 6  3 -9]]
Negative values of Matrix B:
[[-1  5 -3]
 [ 2  4  6]
 [-8 -5  4]]


## **Adding and deleting rows/columns of matrix**



In [8]:
#Row Delete
A_del = np.delete(A, 2, 0)

print("Matrix A after deleting 3rd row:")
print(A_del)

#Column Delete
A_del = np.delete(A, 1, 1)

print("Matrix A after deleting 2nd column:")
print(A_del)

#Row Add
A_row_add = np.array([2,6,2])
A_add = np.vstack((A, A_row_add))

print("Matrix A after adding row")
print(A_add)

#Column Add
A_col_add = np.array([5,1,3])
A_add = np.column_stack((A, A_col_add))

print("Matrix A after adding column")
print(A_add)

Matrix A after deleting 3rd row:
[[ 1  2 -7]
 [-3  4 -2]]
Matrix A after deleting 2nd column:
[[ 1 -7]
 [-3 -2]
 [-6  9]]
Matrix A after adding row
[[ 1  2 -7]
 [-3  4 -2]
 [-6 -3  9]
 [ 2  6  2]]
Matrix A after adding column
[[ 1  2 -7  5]
 [-3  4 -2  1]
 [-6 -3  9  3]]


## **Minimum and maximum of matrix**

In [11]:
#Min of matrix
print("Minimum of Matrix A:", np.min(A))
print("Minimum of Matrix B:", np.min(B))

#Max of matrix
print("Maximum of Matrix A:", np.max(A))
print("Maximum of Matrix B:", np.max(B))

Minimum of Matrix A: -7
Minimum of Matrix B: -6
Maximum of Matrix A: 9
Maximum of Matrix B: 8


## **Sum of some/all elements of matrix**

In [12]:
print("Sum of Matrix A: ", np.sum(A))
print("Sum of Matrix B: ", np.sum(B))

print("Sum of Matrix A Row-wise: ", np.sum(A, axis=0))
print("Sum of Matrix A Column-wise: ", np.sum(A, axis=1))

print("Sum of Matrix B Row-wise: ", np.sum(B, axis=0))
print("Sum of Matrix B Column-wise: ", np.sum(B, axis=1))

Sum of Matrix A:  -5
Sum of Matrix B:  -4
Sum of Matrix A Row-wise:  [-8  3  0]
Sum of Matrix A Column-wise:  [-4 -1  0]
Sum of Matrix B Row-wise:  [ 7 -4 -7]
Sum of Matrix B Column-wise:  [ -1 -12   9]
